services:
  purrfecttrackdb:
    image: mcr.microsoft.com/mssql/server

  purrfecttrack.api:
    image: ${DOCKER_REGISTRY-}purrfecttrackapi
    build:
      context: .
      dockerfile: PurrfectTrack.Api/Dockerfile